commands:
  hello: ["echo", "hello"]
  touch: ["touch", "tmp"]

listeners:
  http:
    host: 127.0.0.1
    port: 8080
    tls:
      cert_file: $XDG_CONFIG_HOME/poke/server.crt
      key_file: $XDG_CONFIG_HOME/poke/server.key

auth:
  api_token:
    listeners: [http]
    env: POKE_API_TOKEN
